### ISSUE TITLE
[Bug] Map Popup not working on Chrome for Android

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/okKindred#266]

**Comment by JustinWingChungHui** [comment]
Works on firefox mobile...

**Comment by szech** [comment]
Works on Opera mobile.
I think it uses the same rendering engine as Chrome, so maybe a recent
chrome change has broken it?

On 15 Feb 2017 17:20, "Justin Wing Chung Hui" <notifications@github.com>
wrote:

Works on firefox mobile...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JustinWingChungHui/okKindred/issues/266#issuecomment-280076205>,
or mute the thread

**Comment by JustinWingChungHui** [comment]
Google have fixed Chrome.  Now works with latest version.
